version: '3.9'

services:
  nova:
    image: nikolaik/python-nodejs:python3.11-nodejs18
    container_name: nova
    hostname: nova
    build:
      context: .
      dockerfile: ./assets/docker/Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - .:/var/www/Nova-Platform
    depends_on:
      - nova-qdrant
      - nova-llamacpp
    networks:
      - novaNetwork
  
  nova-qdrant:
    image: qdrant/qdrant:latest
    container_name: nova-db
    hostname: nova-db
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./assets/qdrant_data:/qdrant/storage
    networks:
      - novaNetwork
  
  nova-llamacpp:
    image: ghcr.io/ggerganov/llama.cpp:server
    container_name: nova-llamacpp
    hostname: nova-llamacpp
    command: >
      -m data/models/text/mistral-7b/mistral-7b-v0.1.Q2_K.gguf
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - ./assets:/data
    restart: unless-stopped
    networks:
      - novaNetwork

networks:
  novaNetwork:
    driver: bridge